name: Publish to registry, test and deploy app

on:
  push:
    branches:
      - master

jobs:
  frontend_test:
    runs-on: [ubuntu-18.04]
    container: node:12.0-alpine
    steps:
      - uses: actions/checkout@v1
      - name: Cache NPM dependencies
        uses: actions/cache@v1
        with:
          path: ./
          key: ${{ runner.OS }}-cache-yarn-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.OS }}-cache-yarn
      - name: Install NPM dependencies
        run: yarn install
      - name: Tests
        run: yarn test
      - name: Eslint
        run: yarn lint